name: 'docker-build-and-publish'
description: 'Builds docker images and publish master'
author: "Jeroen Knoops <jeroen.knoops@philips.com>"
branding:
  icon: "anchor"
  color: "gray-dark"
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  image-name:
    description: 'The name of the Docker image'
    required: true
  tags:
    description: 'String with tags, separated by a space'
    required: true
  push-branch:
    description: 'Specifies branch to push, separated by a space - DEPRECATED - Will be replaced by push-branches'
  push-branches:
    description: 'Specifies branches to push, separated by a space'
    default: 'master'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dockerfile }}
    - ${{ inputs.image-name }}
    - ${{ inputs.tags }}
    - ${{ inputs.push-branches }}
    - ${{ inputs.push-branch }}
