---
name: Create Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  release_please:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        with:
          command: manifest
          token: ${{ secrets.DCS_GITHUB_TOKEN }}
