name: Shell linter
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v3
      - name: Lint check
        uses: azohra/shell-linter@6bbeaa868df09c34ddc008e6030cfe89c03394a1 # ratchet:azohra/shell-linter@v0.6.0
        with:
          exclude-paths: "bin/install_cosign.sh"
